"""users table

Revision ID: eef7b9653e1c
Revises: 
Create Date: 2020-03-04 17:30:13.275039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef7b9653e1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_phone', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_product_category', table_name='product')
    op.drop_index('ix_product_image', table_name='product')
    op.drop_index('ix_product_reviews', table_name='product')
    op.drop_index('ix_product_size', table_name='product')
    op.drop_index('ix_product_timestamp', table_name='product')
    op.drop_index('ix_product_title', table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.Column('image', sa.VARCHAR(length=64), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.Column('reviews', sa.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_title', 'product', ['title'], unique=False)
    op.create_index('ix_product_timestamp', 'product', ['timestamp'], unique=False)
    op.create_index('ix_product_size', 'product', ['size'], unique=1)
    op.create_index('ix_product_reviews', 'product', ['reviews'], unique=1)
    op.create_index('ix_product_image', 'product', ['image'], unique=1)
    op.create_index('ix_product_category', 'product', ['category'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.INTEGER(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_phone', 'user', ['phone'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    # ### end Alembic commands ###
